#ifndef NETWORK_PROGRAMMING_SINGLE_THREAD_UDP_RECEIVER_H
#define NETWORK_PROGRAMMING_SINGLE_THREAD_UDP_RECEIVER_H

#include "common_net.h"

#define DEFAULT_PORT 5557
#define CONNECTION_QUEUE 100

void handle_connection(SOCKET, sockaddr_in*);
#endif //NETWORK_PROGRAMMING_SINGLE_THREAD_UDP_RECEIVER_H
